words = [

     {"word": "black", "hint": "color"},
     {"word": "blue", "hint": "color"},
     {"word": "red", "hint": "color"},
     {"word": "yellow", "hint": "color"},
     {"word": "apple", "hint": "fruit"},
     {"word": "banana", "hint": "fruit"},
     {"word": "orange", "hint": "fruit"},
     {"word": "kiwi", "hint": "fruit"},
     {"word": "pineapple", "hint": "fruit"},
     {"word": "fun", "hint": "emotion"},
     {"word": "mistaken", "hint": "emotion"},
     {"word": "happy", "hint": "emotion"},
     {"word": "excited", "hint": "emotion"},
     {"word": "sadness", "hint": "emotion"},
     {"word": "work", "hint": "activity"},
     {"word": "vacation", "hint": "activity"},
     {"word": "travel", "hint": "activity"},
     {"word": "adversity", "hint": "diffuculties"},
     {"word": "prosperity", "hint": "abundance"},
     {"word": "book", "hint": "entertainment"},
     {"word": "movie", "hint": "entertainment"},
     {"word": "podcast", "hint": "entertainment"},
     {"word": "radio", "hint": "entertainment"},
     {"word": "sweden", "hint": "country"},
     {"word": "europe", "hint": "continent"},
     {"word": "asia", "hint": "continent"},
     {"word": "north", "hint": "direction"},
     {"word": "south", "hint": "direction"},
     {"word": "west", "hint": "direction"},
     {"word": "east", "hint": "direction"},
     {"word": "farewell", "hint": "goodbye"},

]